# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: make tar.gz

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repository: greycodee/tmcmd
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        files: |
          bin/darwin-arm64-tmcmd.tar.gz
          bin/darwin-intel-tmcmd.tar.gz
          bin/linux-arm64-tmcmd.tar.gz
          bin/linux-amd64-tmcmd.tar.gz
          bin/windows-amd64-tmcmd.zip
